export const SUBMIT_ACTION='SUBMIT_ACTION';

export const SUBMIT_SUCCESS='SUBMIT_SUCCESS';

export const SUBMIT_FAILED='SUBMIT_FAILED';

export const GET_DIARY_DATA_BEGIN='GET_DIARY_DATA_BEGIN'

export const GET_ALL_DIARY='GET_ALL_DIARY';

export const ADD_DATA_OK='ADD_DATA_OK';