export const ActionTypes = {
    ADD_DIARY_CARD: 'ADD_DIARY_CARD',
    REQUEST_ALL_CARDS: 'FETCH_ALL_CARDS',
    LOAD_ALL_DIARY_CARDS: 'LOAD_ALL_DIARY_CARDS',
    REMOVE_DIARY_CARD: 'REMOVE_DIARY_CARD',
    LOGIN: 'LOGIN',
    LOGOUT:'LOGOUT',
    LOADING_START: 'LOADING_START',
    LOADING_END: 'LOADING_END'
}


